os:
    - linux
language: node_js
node_js:
    - "8.11.3"
before_install:
    - npm install -g npm
install:
    - npm install -g yo
    - npm install
    - npm link
script:
    # ----- local tests
    - npm test

    # ----- integration tests
    # clone generator-jhipster
    - cd $HOME
    - git clone https://github.com/pascalgrimaud/generator-jhipster generator-jhipster
    - cd generator-jhipster
    - git checkout -b blueprint-fix-writeFiles origin/blueprint-fix-writeFiles
    - git --no-pager log -n 10 --graph --pretty='%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit
    - npm install && npm link
    # generate default blueprint
    - mkdir -p $HOME/generator-jhipster-helloworld && cd $HOME/generator-jhipster-helloworld
    - npm link generator-jhipster-blueprint
    - yo jhipster-blueprint default
    - npm install
    - npm link
    - npm link generator-jhipster
    # generate a JHipster project, using blueprint helloworld
    - mkdir -p $HOME/app && cd $HOME/app
    - npm link generator-jhipster-helloworld
    - curl https://raw.githubusercontent.com/jhipster/generator-jhipster/master/travis/samples/ngx-default/.yo-rc.json -o .yo-rc.json
    - sed -i -e 's/yarn/npm/g' .yo-rc.json
    - jhipster --blueprint helloworld --force --no-insight
