os:
    - linux
language: node_js
node_js:
    - "8.11.3"
before_install:
    - npm install -g npm
    # Repo for Yarn
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH=$HOME/.yarn/bin:$PATH
install:
    - npm install -g generator-jhipster yo
    - npm install
    - npm link
script:
    # ----- local tests
    - npm test

    # ----- integration tests
    # clone generator-jhipster
    - cd $HOME
    - git clone https://github.com/jhipster/generator-jhipster generator-jhipster
    - cd generator-jhipster
    - npm install && npm link
    # generate default blueprint
    - mkdir -p $HOME/generator-jhipster-helloworld && cd $HOME/generator-jhipster-helloworld
    - npm link generator-jhipster-blueprint
    - yo jhipster-blueprint default
    - npm install
    - npm link
    - npm link generator-jhipster
    # generate a JHipster project, using blueprint helloworld
    - mkdir -p $HOME/app && cd $HOME/app
    - npm link generator-jhipster-helloworld
    - curl https://raw.githubusercontent.com/jhipster/generator-jhipster/master/travis/samples/ngx-default/.yo-rc.json -o .yo-rc.json
    - jhipster --blueprint helloworld --force --no-insight
